### ISSUE TITLE
Implement the ability to change the theme (like a dark mode)

### ISSUE THREAD

**Issue by johno** [johno/digital-garden#25]

**Comment by johnletey** [comment]
This is definitely a feature that needs to be added! It can be similar to [Dan Abramov](
https://mobile.twitter.com/dan_abramov)'s day/night mode toggle on his [blog](https://overreacted.io) (except using feather icons instead of plain old icons).

**Comment by johno** [comment]
Got a WIP implementation that isn't dynamic but now allows you to set the theme of your digital garden:

<img width="1045" alt="Screen Shot 2019-03-26 at 9 18 01 AM" src="https://user-images.githubusercontent.com/1424573/55009398-15c76580-4fa8-11e9-9359-9dcfa71d6e84.png">

**Comment by johnletey** [comment]
@johno Great, thank you! Will there be a way to change the link colours on the user side? Really looking forward to the toggle capability!

**Comment by johno** [comment]
@johnletey There definitely will be.

**Comment by johnletey** [comment]
@johno Great ... thank you!

**Comment by johno** [comment]
So I think dg will only support different themes that happen at the site level for now (installing something like `gastby-theme-digital-garden-dark`). Something like light/dark mode can be considered in the future.
