### ISSUE TITLE
Persistent folders list

### ISSUE THREAD

**Issue by johnletey** [johno/digital-garden#30]
Currently, when you click on one of the folders in the notes page, it takes you to a list of all the notes in that directory. But, the list of folders goes away, so you have to go back to the previous page and then select a different folder (if you want to).

Is there any chance that we could make the list of folders always there and the content beneath them change depending on which folder is selected (if any folder is selected)?

**Comment by johnletey** [comment]
This is probably related to #14

**Comment by johno** [comment]
This is addressed with the breadcrumb trail now.
