### ISSUE TITLE
Global styles inject if navigated after landing on another page

### ISSUE THREAD

**Issue by ChristopherBiscardi** [johno/digital-garden#36]
here's a gif of the effect. I think the bg/color are set in an emotion global component but I haven't actually checked yet because I'm just shipping it as-is :D

![white-bg-global-styles](https://user-images.githubusercontent.com/551247/55269821-d40f1700-5254-11e9-9e99-19050d36da48.gif)

**Comment by ChristopherBiscardi** [comment]
turns out it's because of https://github.com/jxnblk/gatsby-themes/blob/772cf9131f455d43693226c0e24b434fdb0722bb/themes/gatsby-theme-system/src/index.js#L114-L136

**Comment by johno** [comment]
This should be fixed with the latest version of digital-garden/theme-ui.
