### ISSUE TITLE
Implement sorting of articles and wiki content

### ISSUE THREAD

**Issue by johno** [johno/digital-garden#4]
We can use frontmatter:

```
---
priority: 9999
---
```

Or name files like `0000-page.md`.

The latter comes with the benefit of showing up in order on GitHub or `ls`, but it makes for noisy file names.

**Comment by johno** [comment]
Deal with this later.

**Comment by adrw** [comment]
Even basic sorting by filename would be a big step forward. Sorting order seems non-deterministic at this point which is a bit frustrating if any order of the notes is desired.

Example: https://cashapp.github.io/misk-web/docs/guides/building-a-tab

<img width="691" alt="Screen Shot 2019-08-09 at 10 36 36" src="https://user-images.githubusercontent.com/8827217/62786931-9ab3a700-ba91-11e9-8a8d-165a28452d32.png">
