### ISSUE TITLE
theme.css is not a function

### ISSUE THREAD

**Issue by ChristopherBiscardi** [johno/digital-garden#40]
emotion-mdx expects a [css function on the `theme`](https://github.com/jxnblk/emotion-mdx/blob/1d7984eb33a56d12592b4b9f79093b7f0b7b0e33/index.js#L49), so when trying to use 0.0.15 on my blog I see:

![image](https://user-images.githubusercontent.com/551247/55678682-d3106200-58b2-11e9-8070-c13f145a062b.png)

:

**Comment by ChristopherBiscardi** [comment]
Turns out this was because of `Styled.a` usage in garden. Still not sure why, but it took awhile to follow the chain and figure out where the problem was occurring due to not having a usable stack.

**Comment by jxnblk** [comment]
Not sure what's happening, but might be that the emotion-mdx `ComponentProvider` isn't wrapping and providing what it needs? Or maybe duplicated deps – I can add some warnings/checks for context, but if you have any suggestions for how to handle this, I'm all ears

**Comment by ChristopherBiscardi** [comment]
@jxnblk I tried providing a `css` function both in the context raw and as a `transformer` option but couldn't get it to work :/ Mostly some more informative error messages might help here. Need to find a minute to dig deeper into the `Styled` component construction and see if I have any suggestions.

As a side note, I already have a set of components I'm passing in to an MDXProvider for MDX content on my site, so that might be a source of problems too.

**Comment by ChristopherBiscardi** [comment]
> Or maybe duplicated deps

I think there was something weird going on here. It started working last night when I transitioned my blog to a full workspace setup to add theme-ui/digital-garden while I work. Going to close this for now as it seems ephemeral

**Comment by jxnblk** [comment]
Yeah, my best guess is duplicate/missing context – would be great to have better context checks somehow built in to theme-ui, so I might noodle on an idea in that repo
